name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest]
        go: [1.15, 1.14]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Go ${{ matrix.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run test suite
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v1	
        if: matrix.os == 'ubuntu-18.04' && matrix.go == '1.15'
